name: Lighthouse Budget Check Staging

on:
  repository_dispatch:
    types: [stage-uploaded-event]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://genietim.github.io/genieblog.ch/index.en
            https://genietim.github.io/genieblog.ch/blog/en/index.en
          budgetPath: ./budget-stage.json # test performance budgets
          uploadArtifacts: false # save results as an action artifacts
          temporaryPublicStorage: false # upload lighthouse report to the temporary storage
