name: Check Markdown links

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 5" # At 02:00 on Friday.

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: 'mlc_config.json'
