name: Fetch Webmentions

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  webmentions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Fetch webmentions
        env:
          WEBMENTIONS_TOKEN: ${{ secrets.WEBMENTIONS_TOKEN }}
        run: node ./tools/webmentions.js

      - name: Setup git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "tim@genieblog.ch"
          git config user.name "Tim Bernhard"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/genietim/genieblog.ch.git
          git checkout master
          git add .

      - name: Check for changes
        id: changes-check
        run: echo "::set-output name=has-changes::$(git diff --quiet && git diff --staged --quiet)"

      - name: Commit to repository
        env:
          COMMIT_MSG: |
            Fetch webmentions
            skip-checks: true
        run: |
          ${{ steps.changes-check.has-changes.dir }} || (git commit -m "${COMMIT_MSG}"; git push origin master)

      - name: Start post update
        uses: peter-evans/repository-dispatch@v1
        if: ${{ !steps.changes-check.has-changes.dir }}
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: genietim/genieblog.ch
          event-type: post-change-event
