name: Publish Posts

on:
  create:
    tags:
  repository_dispatch:
    types: [post-change-event]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    name: Publish Website to Staging Server
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          tools: composer

      - name: Get npm cache directory path
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm cache dir)"

      - name: Cache npm dependencies
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/npm.lock') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install npm dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Get composer cache directory
        id: composer-cache-dir
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        id: composer-cache
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Run build
        run: npm run production

      - name: Upload posts
        uses: genietim/ftp-action@master
        with:
          host: sftp://lx3.hoststar.hosting:5544
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./build_production/blog/
          remoteDir: "genieblog.ch/public_html/blog/"
